config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  resources  :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: :delete

  resources :achievements

  resources :levels

  resources :challenges

  resources :foods

  resources :behavior_modification_levels

  resources :users do
    member do 
      resources :meal_records
      resources :appointments
      resources :weights
      get 'new_diet_information'
      put 'diet_information'
      get 'new_lifestyle_information'
      put 'lifestyle_information'
      get 'new_custom_information'
      put 'custom_information'
      get 'new_illness_information'
      put 'illness_information'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :achievements, dependent: :destroy
  has_one :behavior_modification_levels, dependent: :destroy
  has_many :meal_points, dependent: :destroy
  has_many :weights, dependent: :destroy

  has_many :meal_records

  has_many :skypes
  has_many :doctors, through: :skypes

  has_secure_password

  before_create :create_auto_login_token

  # validates :name, presence: true, length: { maximum: 50 }
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  #
  # validates :password, length: { minimum: 6 }

  before_save do
#    self.password_digest = BCrypt::Password.create(password)

    self.email = email.downcase

    if self.height
      h = self.height / 100
      self.initial_bmi = self.initial_weight / h / h unless self.initial_weight.nil?
      self.current_bmi = self.current_weight / h / h unless self.current_weight.nil?
    end

    unless self.current_weight.nil? || self.initial_weight.nil? || self.initial_weight == 0
      self.loss_rate = ((self.current_weight / self.initial_weight) - 1) * 100
    end
  end

  def self.new_auto_login_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_auto_login_token
      self.auto_login_token = User.encrypt(User.new_auto_login_token)
    end
#  def authenticate(password)
#    BCrypt::Password.new(password_digest) == password
#  end
 
#  def self.authenticate_user(params)
#    user = User.where(email: params[:email]).first
#    if user && user.authenticate(params[:password])
#      user
#    else
#      nil
#    end
#  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :signed_in_user, only: [:new, :create]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @weight = @user.weights.build
    @meal_record = @user.meal_records.build
    @food = Food.all
    @food_recording = @meal_record.food_recordings.build
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      respond_to do |format|
        format.html { render :edit, notice: 'ユーザー登録が完了しました' }
        format.json { render :show, status: :created, location: @user }
      end
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'ユーザー情報を更新しました' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'ユーザー情報を削除しました' }
      format.json { head :no_content }
    end
  end

  def new_diet_information
  end

  def diet_information
      if @user.diet_information(user_params)
        format.html { redirect_to @user, notice: 'ユーザー情報を更新しました' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
  end
  
  def new_lifestyle_information
  end

  def lifestyle_information
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'ユーザー情報を更新しました' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
  end

  def new_custom_information
  end

  def custom_information
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'ユーザー情報を更新しました' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
  end

  def new_illness_information
  end

  def illness_information
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'ユーザー情報を更新しました' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :email, :gender, :occupation, :purpose, :height, :initial_weight, :target_weight, :current_weight, :loss_rate, :current_bmi, :ticket_count, :target_disease, :birthday, :auto_login_token, :initial_bmi, :pro_edition, :weight_at_age_twenty, :max_weight, :age_of_max_weight, :reason, :how_much_lose_weight, :intensity_of_losing, :sleep_time, :sleep_comment, :alcohole, :how_much_alcohole, :frequency_in_drink, :exercising_custom, :club_activity, :active_of_work, :breakfast_custom, :breakfast_time, :breakfast_staple, :lunch_custom, :lunch_time, :lunch_staple, :dinner_custom, :dinner_time, :dinner_staple, :between_meal, :between_time, :between_food, :midnight_meal, :midnight_time, :midnight_food, :illness, :medicine, :allergy, :stress, :smoking_custom, :smoking_condition, :contact_id, :doctor, :wake_time)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :name, "名前" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email, "メールアドレス" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, "パスワード" %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "パスワードを確認する" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "登録", class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/users/_form_custom.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h3>食習慣について下記よりお選びください</h3>
  <div class="field">
    <%= f.label :breakfast_custom, "朝食について" %>
    <%= f.select :breakfast_custom, {"食べない" => 0, "自炊または家族が作る" => 1, "インスタントや中食や外食が多い" => 2, "不規則" => 3} %>
  </div>
  <div class="field">
    <%= f.label :breakfast_time, "朝食は何時頃に食べることが多いですか" %>
    <%= f.time_field :breakfast_time %>
  </div>
  <div class="field">
    <%= f.label :breakfast_staple, "主に何を食べることが多いですか" %>
    <%= f.text_field :breakfast_staple %>
  </div>
  <div class="field">
    <%= f.label :lunch_custom, "昼食について" %>
    <%= f.select :lunch_custom, {"食べない" => 0, "自炊または家族が作る" => 1, "インスタントや中食や外食が多い" => 2, "不規則" => 3} %>
  </div>
  <div class="field">
    <%= f.label :lunch_time, "昼食は何時頃に食べることが多いですか" %>
    <%= f.time_field :lunch_time %>
  </div>
  <div class="field">
    <%= f.label :lunch_staple, "主に何を食べることが多いですか" %>
    <%= f.text_field :lunch_staple %>
  </div>
  <div class="field">
    <%= f.label :dinner_custom, "夕食について" %>
    <%= f.select :dinner_custom, {"食べない" => 0, "自炊または家族が作る" => 1, "インスタントや中食や外食が多い" => 2, "不規則" => 3} %>
  </div>
  <div class="field">
    <%= f.label :dinner_time, "夕食は何時頃に食べることが多いですか" %>
    <%= f.time_field :dinner_time %>
  </div>
  <div class="field">
    <%= f.label :dinner_staple, "主に何を食べることが多いですか" %>
    <%= f.text_field :dinner_staple %>
  </div>
  <div class="field">
    <%= f.label :between_meal, "間食を食べる習慣はありますか" %>
    <%= f.select :between_meal, {"食べない" => 0, "毎日食べる" => 1, "週に4回以上" => 2, "週に3回以下" => 3} %>
  </div>
  <div class="field">
    <%= f.label :between_time, "間食は何時頃に食べることが多いですか" %>
    <%= f.time_field :between_time %>
  </div>
  <div class="field">
    <%= f.label :between_food, "間食は何をどれくらい食べますか" %>
    <%= f.text_field :between_food, placeholder: "例) チョコレートを50gとオレンジジュースを1Lほど" %>
  </div>
  <div class="field">
    <%= f.label :midnight_meal, "夜食を食べる習慣はありますか" %>
    <%= f.select :midnight_meal, {"食べない" => 0, "毎日食べる" => 1, "週に4回以上" => 2, "週に3回以下" => 3} %>
  </div>
  <div class="field">
    <%= f.label :midnight_time, "夜食は何時頃に食べることが多いですか" %>
    <%= f.time_field :midnight_time  %>
  </div>
  <div class="field">
    <%= f.label :midnight_food, "夜食は何をどれくらい食べますか" %>
    <%= f.text_field :midnight_food, placeholder: "例) 豚骨ラーメンを1杯" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_form_diet.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gender, "性別" %>
    <%= f.select :gender, {"男性" => 0, "女性" => 1} %>
  </div>
  <div class="field">
    <%= f.label :birthday, "誕生日" %>
    <%= f.date_field :birthday, value: Time.zone.local(1980, 1, 1) %>
  </div>
  <div class="field">
    <%= f.label :height, "身長(cm)" %>
    <%= f.number_field :height, in: 145..200, step: 0.5, value: 170 %>
  </div>
  <div class="field">
    <%= f.label :initial_weight, "体重(kg)" %>
    <%= f.number_field :initial_weight, in: 48..110, step: 0.5, value: 65 %>
  </div>
  <div class="field">
    <%= f.label :target_weight, "目標体重(kg)" %>
    <%= f.number_field :target_weight, in: 45..90, value: 65 %>
  </div>
  <div class="field">
    <%= f.label :weight_at_age_twenty, "20歳時の体重(kg)" %>
    <%= f.number_field :weight_at_age_twenty, in: 48..110, value: 65 %>
  </div>
  <div class="field">
    <%= f.label :max_weight, "過去最高体重(kg)" %>
    <%= f.number_field :max_weight, in: 48..110, value: 65 %>
  </div>
  <div class="field">
    <%= f.label :age_of_max_weight, "最高体重時の年齢" %>
    <%= f.number_field :age_of_max_weight, in: 16..60, value: 30 %>
  </div>
  <div class="field">
    <%= f.label :reason, "ダイエットをしたい理由はなんですか" %>
    <%= f.text_field :reason, placeholder: "できるだけ具体的に記入してください" %>
  </div>
  <div class="field">
    <%= f.label :how_much_lose_weight, "1ヶ月で何キロ痩せたいですか" %>
    <%= f.number_field :how_much_lose_weight, in: 1..9 %>
  </div>
  <div class="field">
    <%= f.label :intensity_of_losing, "希望するダイエットの強度を選んでください" %>
    <%= f.select :intensity_of_losing, {"美容的なダイエット" => 0, "健康的なダイエット" => 1, "出来る限り多く痩せたい" => 2} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_form_illness.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :illness, "現在、持病や過去に診断された病気はありますか" %>
    <%= f.text_field :illness, placeholder: "高血圧と糖尿病" %>
  </div>
  <div class="field">
    <%= f.label :medicine, "現在、常用している薬やサプリメントはありますか" %>
    <%= f.text_field :medicine, placeholder: "常用していない場合は「無し」とご記入下さい" %>
  </div>
  <div class="field">
    <%= f.label :allergy, "薬や食品でアレルギーはありますか" %>
    <%= f.text_field :allergy, placeholder: "アレルギーがない場合は「無し」とご記入下さい" %>
  </div>
  <div class="field">
    <%= f.label :stress, "現在感じているストレスはありますか" %>
    <%= f.text_field :stress, placeholder: "例) 不眠で強いストレスがある。職場の人間関係で弱いストレスがある。" %>
  </div>
  <div class="field">
    <%= f.label :smoking_custom, "喫煙習慣はありますか" %>
    <%= f.select :smoking_custom, {"無し" => 0, "有り" => 1, "禁煙中" => 2} %>
  </di>
  <div class="field">
    <%= f.label :smoking_condition, "喫煙者は1日当たりの本数と喫煙開始年齢を、禁煙者は禁煙期間をお答えください。" %>
    <%= f.text_field :smoking_condition, placeholder: "例)　22歳から1日10本程度" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>問診内容入力</h1>

      <div class="row">
        <div class="col-xs-6 col-md-6">

          
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gender, "性別" %>
    <%= f.select :gender, {"男性" => 0, "女性" => 1} %>
  </div>
  <div class="field">
    <%= f.label :birthday, "誕生日" %>
    <%= f.date_field :birthday, value: Time.zone.local(1980, 1, 1) %>
  </div>
  <div class="field">
    <%= f.label :height, "身長(cm)" %>
    <%= f.number_field :height, in: 145..200, step: 0.5, value: 170 %>
  </div>
  <div class="field">
    <%= f.label :initial_weight, "体重(kg)" %>
    <%= f.number_field :initial_weight, in: 48..110, step: 0.5, value: 65 %>
  </div>
  <div class="field">
    <%= f.label :target_weight, "目標体重(kg)" %>
    <%= f.number_field :target_weight, in: 45..90, value: 65 %>
  </div>
  <div class="field">
    <%= f.label :weight_at_age_twenty, "20歳時の体重(kg)" %>
    <%= f.number_field :weight_at_age_twenty, in: 48..110, value: 65 %>
  </div>
  <div class="field">
    <%= f.label :max_weight, "過去最高体重(kg)" %>
    <%= f.number_field :max_weight, in: 48..110, value: 65 %>
  </div>
  <div class="field">
    <%= f.label :age_of_max_weight, "最高体重時の年齢" %>
    <%= f.number_field :age_of_max_weight, in: 16..60, value: 30 %>
  </div>
  <div class="field">
    <%= f.label :reason, "ダイエットをしたい理由はなんですか" %>
    <%= f.text_field :reason, placeholder: "できるだけ具体的に記入してください" %>
  </div>
  <div class="field">
    <%= f.label :how_much_lose_weight, "1ヶ月で何キロ痩せたいですか" %>
    <%= f.number_field :how_much_lose_weight, in: 1..9 %>
  </div>
  <div class="field">
    <%= f.label :intensity_of_losing, "希望するダイエットの強度を選んでください" %>
    <%= f.select :intensity_of_losing, {"美容的なダイエット" => 0, "健康的なダイエット" => 1, "出来る限り多く痩せたい" => 2} %>
  </div>


  <div class="field">
    <%= f.label :sleep_time, "就寝時間" %>
    <%= f.number_field :sleep_time %>
  </div>
  <div class="field">
    <%= f.label :wake_time, "起床時間" %>
    <%= f.number_field :wake_time %>
  </div>
  <div class="field">
    <%= f.label :sleep_comment, "睡眠に問題はありますか" %>
    <%= f.text_field :sleep_comment %>
  </div>
  <div class="field">
    <%= f.label :alcohole, "お酒は飲みますか。種類とおおよその量をお答え下さい" %>
    <%= f.text_field :alcohole %>
  </div>
  <div class="field">
    <%= f.label :how_much_alcohole, "どのくらい飲みますか(杯/日)" %>
    <%= f.range_field :how_much_alcohole, in: 0..10 %>
  </div>
  <div class="field">
    <%= f.label :frequency_in_drink, "週に何日、お酒を飲みますか" %>
    <%= f.range_field :frequency_in_drink, in: 0..7 %>
  </div>
  <div class="field">
    <%= f.label :exercising_custom, "運動習慣はありますか？運動の種類と頻度をお答え下さい" %>
    <%= f.text_field :exercising_custom, placeholder: "1時間のランニングを週に2回" %>
  </div>
  <div class="field">
    <%= f.label :club_activity, "学生時代は運動していましたか" %>
    <%= f.text_field :club_activity %>
  </div>
  <div class="field">
    <%= f.label :active_of_work, "仕事での活動量を下記からお選びください" %>
    <%= f.select :active_of_work, {"軽作業(デスクワーク、家事など)" => "0", "普通の作業(立ち仕事など)" => "1", "重作業(運搬、力仕事など)" => "2"} %>
  </div>



  <h3>食習慣について下記よりお選びください</h3>
  <div class="field">
    <%= f.label :breakfast_custom, "朝食について" %>
    <%= f.select :breakfast_custom, {"食べない" => 0, "自炊または家族が作る" => 1, "インスタントや中食や外食が多い" => 2, "不規則" => 3} %>
  </div>
  <div class="field">
    <%= f.label :breakfast_time, "朝食は何時頃に食べることが多いですか" %>
    <%= f.time_field :breakfast_time %>
  </div>
  <div class="field">
    <%= f.label :breakfast_staple, "主に何を食べることが多いですか" %>
    <%= f.text_field :breakfast_staple %>
  </div>
  <div class="field">
    <%= f.label :lunch_custom, "昼食について" %>
    <%= f.select :lunch_custom, {"食べない" => 0, "自炊または家族が作る" => 1, "インスタントや中食や外食が多い" => 2, "不規則" => 3} %>
  </div>
  <div class="field">
    <%= f.label :lunch_time, "昼食は何時頃に食べることが多いですか" %>
    <%= f.time_field :lunch_time %>
  </div>
  <div class="field">
    <%= f.label :lunch_staple, "主に何を食べることが多いですか" %>
    <%= f.text_field :lunch_staple %>
  </div>
  <div class="field">
    <%= f.label :dinner_custom, "夕食について" %>
    <%= f.select :dinner_custom, {"食べない" => 0, "自炊または家族が作る" => 1, "インスタントや中食や外食が多い" => 2, "不規則" => 3} %>
  </div>
  <div class="field">
    <%= f.label :dinner_time, "夕食は何時頃に食べることが多いですか" %>
    <%= f.time_field :dinner_time %>
  </div>
  <div class="field">
    <%= f.label :dinner_staple, "主に何を食べることが多いですか" %>
    <%= f.text_field :dinner_staple %>
  </div>
  <div class="field">
    <%= f.label :between_meal, "間食を食べる習慣はありますか" %>
    <%= f.select :between_meal, {"食べない" => 0, "毎日食べる" => 1, "週に4回以上" => 2, "週に3回以下" => 3} %>
  </div>
  <div class="field">
    <%= f.label :between_time, "間食は何時頃に食べることが多いですか" %>
    <%= f.time_field :between_time %>
  </div>
  <div class="field">
    <%= f.label :between_food, "間食は何をどれくらい食べますか" %>
    <%= f.text_field :between_food, placeholder: "例) チョコレートを50gとオレンジジュースを1Lほど" %>
  </div>
  <div class="field">
    <%= f.label :midnight_meal, "夜食を食べる習慣はありますか" %>
    <%= f.select :midnight_meal, {"食べない" => 0, "毎日食べる" => 1, "週に4回以上" => 2, "週に3回以下" => 3} %>
  </div>
  <div class="field">
    <%= f.label :midnight_time, "夜食は何時頃に食べることが多いですか" %>
    <%= f.time_field :midnight_time  %>
  </div>
  <div class="field">
    <%= f.label :midnight_food, "夜食は何をどれくらい食べますか" %>
    <%= f.text_field :midnight_food, placeholder: "例) 豚骨ラーメンを1杯" %>
  </div>
  <div class="field">
    <%= f.label :illness, "現在、持病や過去に診断された病気はありますか" %>
    <%= f.text_field :illness, placeholder: "高血圧と糖尿病" %>
  </div>
  <div class="field">
    <%= f.label :medicine, "現在、常用している薬やサプリメントはありますか" %>
    <%= f.text_field :medicine, placeholder: "常用していない場合は「無し」とご記入下さい" %>
  </div>
  <div class="field">
    <%= f.label :allergy, "薬や食品でアレルギーはありますか" %>
    <%= f.text_field :allergy, placeholder: "アレルギーがない場合は「無し」とご記入下さい" %>
  </div>
  <div class="field">
    <%= f.label :stress, "現在感じているストレスはありますか" %>
    <%= f.text_field :stress, placeholder: "例) 不眠で強いストレスがある。職場の人間関係で弱いストレスがある。" %>
  </div>
  <div class="field">
    <%= f.label :smoking_custom, "喫煙習慣はありますか" %>
    <%= f.select :smoking_custom, {"無し" => 0, "有り" => 1, "禁煙中" => 2} %>
  </div>
  <div class="field">
    <%= f.label :smoking_condition, "喫煙者は1日当たりの本数と喫煙開始年齢を、禁煙者は禁煙期間をお答えください。" %>
    <%= f.text_field :smoking_condition, placeholder: "例)　22歳から1日10本程度" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password digest</th>
      <th>Email</th>
      <th>Gender</th>
      <th>Occupation</th>
      <th>Purpose</th>
      <th>Height</th>
      <th>Initial weight</th>
      <th>Target weight</th>
      <th>Current weight</th>
      <th>Loss rate</th>
      <th>Current bmi</th>
      <th>Ticket count</th>
      <th>Target disease</th>
      <th>Birthday</th>
      <th>Auto login token</th>
      <th>Initial bmi</th>
      <th>Pro edition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.email %></td>
        <td><%= user.gender %></td>
        <td><%= user.occupation %></td>
        <td><%= user.purpose %></td>
        <td><%= user.height %></td>
        <td><%= user.initial_weight %></td>
        <td><%= user.target_weight %></td>
        <td><%= user.current_weight %></td>
        <td><%= user.loss_rate %></td>
        <td><%= user.current_bmi %></td>
        <td><%= user.ticket_count %></td>
        <td><%= user.target_disease %></td>
        <td><%= user.birthday %></td>
        <td><%= user.auto_login_token %></td>
        <td><%= user.initial_bmi %></td>
        <td><%= user.pro_edition %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/new_custom_information.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-4 well well-sm">
      <legend><a href="/"><i class="glyphicon glyphicon-globe"></i></a> ユーザー登録!</legend>
      <div class="row">
        <div class="col-xs-6 col-md-6">

          <%= render 'form_custom' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= @user.name %>さん</p>
<h3>行動記録をつける</h3>
<%= link_to "食事を記録する", new_meal_record_path %>

<p>体重を記録する</p>
<%= render 'shared/form_weight_recording' %>

<h3>過去の履歴見る</h3>
<p>健康行動を見る</p>

<p>過去の食事を見る<p>

<%= link_to "体重を確認", weights_path %>