config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  resources  :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: :delete

  resources :achievements

  resources :levels

  resources :challenges

  resources :foods

  resources :behavior_modification_levels

  resources :users do
    member do 
      resources :meal_records
      resources :appointments
      resources :weights
      get 'new_diet_information'
      put 'diet_information'
      get 'new_lifestyle_information'
      put 'lifestyle_information'
      get 'new_custom_information'
      put 'custom_information'
      get 'new_illness_information'
      put 'illness_information'
    end
  end

end

app/models/meal_record.rb
class MealRecord < ActiveRecord::Base
  belongs_to :user

  has_many :food_recordings, dependent: :destroy
  has_many :foods, through: :food_recordings

  accepts_nested_attributes_for :food_recordings, allow_destroy: true

end

app/controllers/meal_records_controller.rb
class MealRecordsController < ApplicationController
  before_action :set_meal_record, only: [:show, :edit, :update, :destroy]

  # GET /meal_records
  # GET /meal_records.json
  def index
    @meal_records = current_user.meal_records.all
  end

  # GET /meal_records/1
  # GET /meal_records/1.json
  def show
  end

  # GET /meal_records/new
  def new
    @meal_record = Form::MealRecord.new
    @food = Food.all
  end

  # GET /meal_records/1/edit
  def edit
    @meal_record = Form::MealRecord.find(params[:id])
  end

  # POST /meal_records
  # POST /meal_records.json
  def create
    @meal_record = Form::MealRecord.new(meal_record_params)

    respond_to do |format|
      if @meal_record.save
        format.html { redirect_to @meal_record, notice: 'Meal record was successfully created.' }
        format.json { render :show, status: :created, location: @meal_record }
      else
        format.html { render :new }
        format.json { render json: @meal_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meal_records/1
  # PATCH/PUT /meal_records/1.json
  def update
    respond_to do |format|
      if @meal_record.update(meal_record_params)
        format.html { redirect_to @meal_record, notice: 'Meal record was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal_record }
      else
        format.html { render :edit }
        format.json { render json: @meal_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meal_records/1
  # DELETE /meal_records/1.json
  def destroy
    @meal_record.destroy
    respond_to do |format|
      format.html { redirect_to meal_records_url, notice: 'Meal record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal_record
      @meal_record = MealRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_record_params
      params.require(:meal_record).permit(:user_id, :meal_code, :date, food_recordings_attributes: [:id, :meal_record_id, :food_id])
    end
end

app/helpers/meal_records_helper.rb
module MealRecordsHelper
end

app/views/meal_records/_form.html.erb
<%= form_for(@meal_record) do |f| %>
  <% if @meal_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal_record.errors.count, "error") %> prohibited this meal_record from being saved:</h2>

      <ul>
      <% @meal_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food_id %><br>
    <%= f.number_field :food_id %>
  </div>
  <div class="field">
    <%= f.label :meal_code %><br>
    <%= f.number_field :meal_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meal_records/edit.html.erb
<h1>Editing meal_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal_record %> |
<%= link_to 'Back', meal_records_path %>

app/views/meal_records/index.html.erb
<h1>Listing meal_records</h1>

<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>User</th>
      <th>Meal code</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meal_records.each do |meal_record| %>
      <tr>
        <td><%= meal_record.food_id %></td>
        <td><%= meal_record.user_id %></td>
        <td><%= meal_record.meal_code %></td>
        <td><%= meal_record.date %></td>
        <td><%= link_to 'Show', meal_record %></td>
        <td><%= link_to 'Edit', edit_meal_record_path(meal_record) %></td>
        <td><%= link_to 'Destroy', meal_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meal record', new_meal_record_path %>

app/views/meal_records/new.html.erb
<h1>New meal_record</h1>

<%= render 'shared/form_meal_recording' %>

<%= link_to 'Back', meal_records_path %>

app/views/meal_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food:</strong>
  <%= @meal_record.food_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @meal_record.user_id %>
</p>

<p>
  <strong>Meal code:</strong>
  <%= @meal_record.meal_code %>
</p>


<p>
  <strong>Date:</strong>
  <%= @meal_record.date %>
</p>

<%= link_to 'Edit', edit_meal_record_path(@meal_record) %> |
<%= link_to 'Back', meal_records_path %>