config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  resources  :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: :delete

  resources :achievements

  resources :levels

  resources :challenges

  resources :foods

  resources :behavior_modification_levels

  resources :users do
    member do 
      resources :meal_records
      resources :appointments
      resources :weights
      get 'new_diet_information'
      put 'diet_information'
      get 'new_lifestyle_information'
      put 'lifestyle_information'
      get 'new_custom_information'
      put 'custom_information'
      get 'new_illness_information'
      put 'illness_information'
    end
  end

end

app/models/level.rb
class Level < ActiveRecord::Base
  belongs_to :challenge
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: [:show, :edit, :update, :destroy]

  # GET /levels
  # GET /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels
  # POST /levels.json
  def create
    @level = Level.new(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to @level, notice: 'Level was successfully created.' }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1
  # PATCH/PUT /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to @level, notice: 'Level was successfully updated.' }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1
  # DELETE /levels/1.json
  def destroy
    @level.destroy
    respond_to do |format|
      format.html { redirect_to levels_url, notice: 'Level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def level_params
      params.require(:level).permit(:challenge_id, :group, :level, :stage, :rank, :caption, :description, :comment, :tips, :star, :term)
    end
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/levels/_form.html.erb
<%= form_for(@level) do |f| %>
  <% if @level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
      <% @level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :challenge_id %><br>
    <%= f.number_field :challenge_id %>
  </div>
  <div class="field">
    <%= f.label :group %><br>
    <%= f.number_field :group %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :stage %><br>
    <%= f.number_field :stage %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <div class="field">
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :tips %><br>
    <%= f.text_field :tips %>
  </div>
  <div class="field">
    <%= f.label :star %><br>
    <%= f.number_field :star %>
  </div>
  <div class="field">
    <%= f.label :term %><br>
    <%= f.text_field :term %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/levels/edit.html.erb
<h1>Editing level</h1>

<%= render 'form' %>

<%= link_to 'Show', @level %> |
<%= link_to 'Back', levels_path %>

app/views/levels/index.html.erb
<h1>Listing levels</h1>

<table>
  <thead>
    <tr>
      <th>Challenge</th>
      <th>Group</th>
      <th>Level</th>
      <th>Stage</th>
      <th>Rank</th>
      <th>Caption</th>
      <th>Description</th>
      <th>Comment</th>
      <th>Tips</th>
      <th>Star</th>
      <th>Term</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @levels.each do |level| %>
      <tr>
        <td><%= level.challenge_id %></td>
        <td><%= level.group %></td>
        <td><%= level.level %></td>
        <td><%= level.stage %></td>
        <td><%= level.rank %></td>
        <td><%= level.caption %></td>
        <td><%= level.description %></td>
        <td><%= level.comment %></td>
        <td><%= level.tips %></td>
        <td><%= level.star %></td>
        <td><%= level.term %></td>
        <td><%= link_to 'Show', level %></td>
        <td><%= link_to 'Edit', edit_level_path(level) %></td>
        <td><%= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Level', new_level_path %>

app/views/levels/new.html.erb
<h1>New level</h1>

<%= render 'form' %>

<%= link_to 'Back', levels_path %>

app/views/levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Challenge:</strong>
  <%= @level.challenge_id %>
</p>

<p>
  <strong>Group:</strong>
  <%= @level.group %>
</p>

<p>
  <strong>Level:</strong>
  <%= @level.level %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @level.stage %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @level.rank %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @level.caption %>
</p>

<p>
  <strong>Description:</strong>
  <%= @level.description %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @level.comment %>
</p>

<p>
  <strong>Tips:</strong>
  <%= @level.tips %>
</p>

<p>
  <strong>Star:</strong>
  <%= @level.star %>
</p>

<p>
  <strong>Term:</strong>
  <%= @level.term %>
</p>

<%= link_to 'Edit', edit_level_path(@level) %> |
<%= link_to 'Back', levels_path %>