config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  resources  :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: :delete

  resources :achievements

  resources :levels

  resources :challenges

  resources :foods

  resources :behavior_modification_levels

  resources :users do
    member do 
      resources :meal_records
      resources :appointments
      resources :weights
      get 'new_diet_information'
      put 'diet_information'
      get 'new_lifestyle_information'
      put 'lifestyle_information'
      get 'new_custom_information'
      put 'custom_information'
      get 'new_illness_information'
      put 'illness_information'
    end
  end

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  belongs_to :user
  belongs_to :challenge
  belongs_to :level
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  has_many :levels, dependent: :destroy
  accepts_nested_attributes_for :levels

  attr_accessor :levels
end

app/models/food.rb
class Food < ActiveRecord::Base
  has_many :food_records
  has_many :meal_records, through: :food_records

  STAPLE = 0
  MAIN_DISH = 1
  SIDE_DISH = 2
  SOUP = 3

  CIRCLE = 0
  TRIANGLE = 1
  CROSS = 2
end

app/models/level.rb
class Level < ActiveRecord::Base
  belongs_to :challenge
end

app/models/meal_point.rb
class MealPoint < ActiveRecord::Base
  belongs_to :user
end

app/models/meal_record.rb
class MealRecord < ActiveRecord::Base
  belongs_to :user

  has_many :food_recordings, dependent: :destroy
  has_many :foods, through: :food_recordings

  accepts_nested_attributes_for :food_recordings, allow_destroy: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :achievements, dependent: :destroy
  has_one :behavior_modification_levels, dependent: :destroy
  has_many :meal_points, dependent: :destroy
  has_many :weights, dependent: :destroy

  has_many :meal_records

  has_many :skypes
  has_many :doctors, through: :skypes

  has_secure_password

  before_create :create_auto_login_token

  # validates :name, presence: true, length: { maximum: 50 }
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  #
  # validates :password, length: { minimum: 6 }

  before_save do
#    self.password_digest = BCrypt::Password.create(password)

    self.email = email.downcase

    if self.height
      h = self.height / 100
      self.initial_bmi = self.initial_weight / h / h unless self.initial_weight.nil?
      self.current_bmi = self.current_weight / h / h unless self.current_weight.nil?
    end

    unless self.current_weight.nil? || self.initial_weight.nil? || self.initial_weight == 0
      self.loss_rate = ((self.current_weight / self.initial_weight) - 1) * 100
    end
  end

  def self.new_auto_login_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_auto_login_token
      self.auto_login_token = User.encrypt(User.new_auto_login_token)
    end
#  def authenticate(password)
#    BCrypt::Password.new(password_digest) == password
#  end
 
#  def self.authenticate_user(params)
#    user = User.where(email: params[:email]).first
#    if user && user.authenticate(params[:password])
#      user
#    else
#      nil
#    end
#  end

end

app/models/weight.rb
class Weight < ActiveRecord::Base
  belongs_to :user
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/meal_records_helper.rb
module MealRecordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    auto_login_token = User.new_auto_login_token
    cookies.permanent[:auto_login_token] = auto_login_token
    user.update_attribute(:auto_login_token, User.encrypt(auto_login_token))
    self.current_user = user
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "ログインしてください"
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:auto_login_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    auto_login_token = User.encrypt(cookies[:auto_login_token])
    @current_user ||= User.find_by(auto_login_token: auto_login_token)
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DietDctor</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "application" %>
</head>
<body>
  <header class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
  <span class="sr-only">Toggle navigation</span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  </button>
  <%= link_to 'DietDctor', root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav navbar-right">
    <% if signed_in? %>
      <li><%= link_to 'ログアウト', signout_path, :method => :delete, confirm: "ログアウトしますか？" %></li>
    <% else %>
      <li><%= link_to 'ログイン', signin_path %></li>
      <li><%= link_to 'ユーザー登録', new_user_path %></li>
    <% end %>
  </ul>
      </div>
    </div>
  </header>
  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
  <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert]  %>
      <div class="alert alert-danger">
  <%= flash[:alert]  %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      エラーの数<%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form_weight_recording.html.erb
<%= form_for(@weight) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :date, "日付選択" %>
    <%= f.date_select :date, {}, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :weight, "体重入力" %>
    <%= f.number_field :weight %>
  </div>
  <%= f.submit "更新", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @user.occupation %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @user.purpose %>
</p>

<p>
  <strong>Height:</strong>
  <%= @user.height %>
</p>

<p>
  <strong>Initial weight:</strong>
  <%= @user.initial_weight %>
</p>

<p>
  <strong>Target weight:</strong>
  <%= @user.target_weight %>
</p>

<p>
  <strong>Current weight:</strong>
  <%= @user.current_weight %>
</p>

<p>
  <strong>Loss rate:</strong>
  <%= @user.loss_rate %>
</p>

<p>
  <strong>Current bmi:</strong>
  <%= @user.current_bmi %>
</p>

<p>
  <strong>Ticket count:</strong>
  <%= @user.ticket_count %>
</p>

<p>
  <strong>Target disease:</strong>
  <%= @user.target_disease %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Auto login token:</strong>
  <%= @user.auto_login_token %>
</p>

<p>
  <strong>Initial bmi:</strong>
  <%= @user.initial_bmi %>
</p>

<p>
  <strong>Pro edition:</strong>
  <%= @user.pro_edition %>
</p>

<p>
  20歳時の体重:<br>
    <%= @user.weight_at_age_twenty %>
    </p>

    <p>
      過去最大体重<br>
        <%= @user.max_weight %>
        </p>


        <p>
          過去最大体重時の年齢<br>
            <%= @user.age_of_max_weight %>
            </p>

            <p>
              ダイエット理由<br>
                <%= @user.reason %>
                </p>

                <p>
                  1ヶ月当たりの希望減量kg<br>
                    <%= @user.how_much_lose_weight %>
                    </p>
                    <p>
                      希望するダイエット強度<br>
                        <%= @user.intensity_of_losing %>
                        </p>
                        <p>
                          就寝時間<br>
                            <%= @user.sleep_time %>
                            </p>
                            <p>
                              起床時間<br>
                                <%= @user.wake_time %>
                                </p>
                                <p>
                                  睡眠時の悩み<br>
                                    <%= @user.sleep_comment %>
                                    </p>
                                    <p>
                                      アルコール<br>
                                        <%= @user.alcohole %>
                                        </p>
                                        <p>
                                          飲酒量<br>
                                            <%= @user.how_much_alcohole %>
                                            </p>
                                            <p>
                                              飲酒頻度<br>
                                                <%= @user.frequency_in_drink %>
                                                </p>
                                                <p>
                                                  運動週間<br>
                                                    <%= @user.exercising_custom %>
                                                    </p>
                                                    <p>
                                                      学生時の運動経験<br>
                                                        <%= @user.club_activity %>
                                                        </p>
                                                        <p>
                                                          仕事の活動量<br>
                                                            <%= @user.active_of_work %>
                                                            </p>

                                                            <p>
                                                              朝食の習慣<br>
                                                                <%= @user.breakfast_custom %>
                                                                </p>
                                                                <p>
                                                                  朝食の時間<br>
                                                                    <%= @user.breakfast_time %>
                                                                    </p>
                                                                    <p>
                                                                      朝食の主食<br>
                                                                        <%= @user.breakfast_staple %>
                                                                        </p>
                                                                        <p>
                                                                          昼食の習慣<br>
                                                                            <%= @user.lunch_custom %>
                                                                            </p>
                                                                            <p>
                                                                              昼食の時間<br>
                                                                                <%= @user.lunch_time %>
                                                                                </p>
                                                                                <p>
                                                                                  昼食の主食<br>
                                                                                    <%= @user.lunch_staple %>
                                                                                    </p>
                                                                                    <p>
                                                                                      夕食の習慣<br>
                                                                                        <%= @user.dinner_custom %>
                                                                                        </p>
                                                                                        <p>
                                                                                          夕食の時間<br>
                                                                                            <%= @user.dinner_time %>
                                                                                            </p>

                                                                                            <p>
                                                                                              夕食の主食<br>
                                                                                                <%= @user.dinner_staple %>
                                                                                                </p>
                                                                                                <p>
                                                                                                  間食について<br>
                                                                                                    <%= @user.between_meal %>
                                                                                                    </p>
                                                                                                    <p>
                                                                                                      間食の時間<br>
                                                                                                        <%= @user.between_time %>
                                                                                                        </p>
                                                                                                        <p>
                                                                                                          間食の食べ物<br>
                                                                                                            <%= @user.between_food %>
                                                                                                            </p>
                                                                                                            <p>
                                                                                                              夜食について<br>
                                                                                                                <%= @user.midnight_meal %>
                                                                                                                </p>

                                                                                                                <p>
                                                                                                                夜食の時間<br>
                                                                                                                  <%= @user.midnight_time %>
                                                                                                                  </p>
                                                                                                                  <p>
                                                                                                                    夜食の食べ物<br>
                                                                                                                      <%= @user.midnight_food %>
                                                                                                                      </p>
                                                                                                                      <p>
                                                                                                                        持病など<br>
                                                                                                                          <%= @user.illness %>
                                                                                                                          </p>
                                                                                                                          <p>
                                                                                                                            服薬している薬やサプリメントなど<br>
                                                                                                                              <%= @user.medicine %>
                                                                                                                              </p>
                                                                                                                              <p>
                                                                                                                                アレルギーについて<br>
                                                                                                                                  <%= @user.allergy %>
                                                                                                                                  </p>
                                                                                                                                  <p>
                                                                                                                                    ストレス<br>
                                                                                                                                      <%= @user.stress %>
                                                                                                                                      </p>
                                                                                                                                      <p>
                                                                                                                                        喫煙習慣<br>
                                                                                                                                          <%= @user.smoking_custom %>
                                                                                                                                          </p>

                                                                                                                                          <p>
                                                                                                                                            喫煙状況<br>
                                                                                                                                              <%= @user.smoking_condition %>
                                                                                                                                              </p>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>